### PR TITLE
Upgrade GStreamer to 1.0

### PR DESCRIPTION
**Pull request by jonty-comp**
NOTE! I have no actual broadcast infrastructure to test this on, just my trusty ThinkPad with Debian and JACK.  That being said, it seems to work fine on there.

I don't recommend pushing this as a new version until at least someone else has tested it!

### CODE REVIEW

**Comment by jonty-comp** [comment]
It looks like your GStreamer install is missing the `level` element - I may have to add a pre-setup check for all the required elements.  Do you have the `gstreamer-plugins-good` package installed?  I'm slightly confused because that same plugin set contains pretty much all the other required plugins for OpenOB to function.
Could you paste the output of the `gst-inspect -a` command here please?

**Comment by scottgrobinson** [comment]
Disregard - I was being really impatient and getting too excited about it possible working, Missing a few packages! "Full" instructions from a base linux image to up and running:

sudo apt-get update
sudo apt-get upgrade
sudo apt-get install python-setuptools git python-gst-1.0 gstreamer1.0-plugins-base gstreamer1.0-plugins-base gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-plugins-good gstreamer1.0-tools python-gobject python-gobject-2 gstreamer1.0-alsa python-redis
git clone https://github.com/JamesHarrison/openob.git
cd openob
git fetch origin +refs/pull/34/merge
git checkout FETCH_HEAD
sudo python setup.py install

**Comment by jonty-comp** [comment]
Cool - no worries, gstreamer is a tangled mess of history!
I believe you should only need `gstreamer1.0-plugins-base` and `gstreamer1.0-plugins-good` nowadays and not all the bad/ugly ones, but it can't hurt to have them.  Opus encoder is even in base now, which is exciting!

**Comment by jonty-comp** [comment]
As you can see from above, i'm whipping up a little Travis build to test the basic functionality - it doesn't really work yet, but i'll hopefully look at it some more tomorrow!

**Comment by JamesHarrison** [comment]
@jonty-comp I've added Travis to the project, so that should auto-build on future commits.

@scottgrobinson If you could provide some feedback on how this is working for you, that'd be great - once it's looking stable we can merge this into master and roll a new "proper" release.

**Comment by scottgrobinson** [comment]
@JamesHarrison Will do! I'll be testing over the next few days in the hope it works nicely for an event at beginning of August.

**Comment by scottgrobinson** [comment]
If I fire up a new Pi, what's the best way of testing this end to end for you? I assume I can't use pip yet until it's released? I could just follow the docs end to end and sub out 'sudo pip install OpenOB' for 

git clone, switch to pr, python setup.py install?

**Comment by jonty-comp** [comment]
That's probably the easiest path, yes.  In the most recent versions of pip you can run `pip install git+https://github.com/JamesHarrison/openob.git@refs/pull/34/merge` directly, but it looks like that's not in my Buster version of pip yet, so I doubt it'll be anywhere else.

**Comment by scottgrobinson** [comment]
Neither of the above commands worked, I had to checkout and run it as per previous comment. It's still referencing 3.1 as opposed to 4.0dev.

Now having problems running without sudo so I'll start this over again.

**Comment by jonty-comp** [comment]
That's bizarre...I don't know enough about pip to make any assumptions.

...oh wait, I just noticed that setup.py still references it as version 3.1.0, that'll be why! You should still be getting the latest code.

**Comment by scottgrobinson** [comment]
Maybe I was just too tired... Worked fine this time!

sudo apt install gstreamer1.0-plugins-base gstreamer1.0-plugins-good gir1.2-gstreamer-1.0 python-gst-1.0 python-redis python-gi python-setuptools git redis-server python-pip
sudo sed -i.bak 's/bind 127.*/bind 0.0.0.0/' /etc/redis/redis.conf && sudo service redis-server restart
sudo pip install git+https://github.com/jonty-comp/openob.git@gst1.0

I've tested alsa RX and TX, anything else that would want testing before a merge?

**Comment by jonty-comp** [comment]
Ah right, gstreamer officially lists alsa as being in the base package but I guess debian/ubuntu splits it out. Bizarre, as it seems jack is in the main package!
I think if you could just continue to test it in your normal use-case, we can confirm that the stability hasn't been affected by the way I refactored the pipeline.

**Comment by LyonelB** [comment]
I just tried with a Raspberry Pi 3 B + and Debian Stretch:
`sudo apt install gstreamer1.0-plugins-base gstreamer1.0-plugins-good gir1.2-gstreamer-1.0 python-gst-1.0 python-redis python-gi python-setuptools git redis-server python-pip`
`sudo sed -i.bak 's/bind 127.*/bind 0.0.0.0/' /etc/redis/redis.conf && sudo service redis-server restart`
`sudo pip install git+https://github.com/jonty-comp/openob.git@gst1.0`


and I have the error:
`openob 192.168.1.161 recepteur transmission rx               Traceback (most recent call last):
  File "/usr/local/bin/openob", line 4, in <module>
    __import__('pkg_resources').run_script('OpenOB==3.1.0', 'openob')
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1486, in run_script
    raise ResolutionError("No script named %r" % script_name)
pkg_resources.ResolutionError: No script named 'openob'
`

**Comment by LyonelB** [comment]
It's works !
With two Raspberry Pi ( 1 RPi 3 B & 1 RPi 3 B+) :
` $ sudo apt-get install python-gst-1.0 gstreamer1.0-plugins-ugly gstreamer1.0-tools python-gobject python-redis redis-server
 $ sudo sed -i.bak 's/bind 127.*/bind 0.0.0.0/' /etc/redis/redis.conf && sudo service redis-server restart
 $ sudo pip install git+https://github.com/jonty-comp/openob.git@gst1.0`

**Comment by scottgrobinson** [comment]
FYI - Latest release is fully working and use in a 'production' environment successfully.

Both ends ran a TX & RX for two way (Only got the commands from studio end, OB end is somewhere in the field...)

RX: /usr/local/bin/openob 10.100.40.53 studio ob1 rx -a alsa -d hw:0
TX: /usr/local/bin/openob 10.100.40.53 studio ob2 tx 10.100.40.77 -a alsa -d hw:1 -p 3002

RX using RapsberryPi onboard
TX using Behringer UCA202

**Comment by JamesHarrison** [comment]
Alright - I'm inclined to merge this into the master branch and cut a new release on PyPi as a new major version, given the positive feedback thus far. Any objections, shout, but if not I'll cut it in a day or two.

**Comment by jonty-comp** [comment]
Fine by me!  I did some random work on another branch off this based on the daemon idea we discussed years ago, but I haven't finished it yet.  Hopefully I'll get a chance to pick it up again sometime soon.

**Comment by whohoho** [comment]
This branch seems to work fine.

I put some patches in the issues to have the help display all options, and 1 to have jack autoconnect (portpattern). Should i submit these as a pull request?

https://github.com/JamesHarrison/openob/issues/36

https://github.com/JamesHarrison/openob/issues/35

**Comment by JamesHarrison** [comment]
@whohoho Yes, absolutely!

**Comment by JamesHarrison** [comment]
@jonty-comp I'm planning to scrap the gh-pages docs and just stick the relevant bits in the wiki in GitHub, tbh. `setup.py` I'd just forgotten to commit!

**Pull request merged**
